### ISSUE TITLE
Showing temperature from two DS18B20 on HU display in SAT mode

### ISSUE THREAD

**Issue by BK-Poland** [visualapproach/Volvo-melbus#18]
Is it possible? :-)
Example: Temp1: 20 C, Temp2: 10 C
Of course, the play / next / prev functions still work.

**Comment by visualapproach** [comment]
Yes it is possible. There are four textlines. Switch between them by pressing RND on HU. Or you can put both temps on a single line if you stay within the display limit (14 chars?) Ofc you need to adapt the code. Look at how I show the battery voltage. Ask if you need specific help.
