### ISSUE TITLE
HU buttons

### ISSUE THREAD

**Issue by Arroquw** [visualapproach/Volvo-melbus#27]
Hello, 

Is it possible to receive the next and prev buttons from the HU with the melbus protocol? I'm planning to use a different bluetooth module (https://www.sunrom.com/get/996418), and it's possible to change tracks based on impedance with a button press, so I'm wondering if it's possible to hook up some resistors to arduino pins and write high to a digital pin if a button press if received.

Also, do I hook up the DIN shell ground to the bluetooth module or the audio common return?

Currently I have Karl Hagstrom's setup, with his code and an audio jack with cable. Im planning to add the bluetooth module and hook it up to the jack's switches, so it will use bluetooth if no jack is present.

**Comment by visualapproach** [comment]
Gnd on DIN shell!
And yes you can use prev/next. It’s already  in the code (my code in this repository). You may need/want to adjust pin numbers in hw and/or sw and adapt to you specific build ofc. Good luck

**Comment by Arroquw** [comment]
OH I kept thinking the 4066 components were physical buttons, but they are actually switch IC's. English is not my native language so I didn't know what bilateral means and assumed they meant something along the lines of physical. So D10-12 are used for play/next/prev buttons on the HU. I see. 

By the way, what are the 100R resistances on CLK/BSY/DATA used for?

**Comment by visualapproach** [comment]
Yes you are right about the 4066. Those resistors is not my idea, they seem to be ”good practice ”. They attenuate reflections probably.

**Comment by Arroquw** [comment]
Alright. What kind of ground loop isolator should I use? The kind with 2 RCA connectors?

**Comment by visualapproach** [comment]
That is up to you. I preferred small connectors but it is not important.
